import Head from "next/head";
import { useEffect, useState } from "react";

export default function UserProfile() {
	const [notes, setNotes] = useState(null);

	const [inputValue, setInputValue] = useState("");

	const url = "http://localhost:5000";

	const inputValueChange = (e) => {
		setInputValue(e.target.value);
	};

	const handleSubmit = (e) => {
		e.preventDefault();
		console.log(inputValue);
		addNote(inputValue);
	};

	async function fetchData() {
		let response = await fetch(`${url}/notes`);
		if (response.ok) {
			setNotes(await response.json());
		} else {
			console.error(response.status);
		}
	}
	const addNote = async (content) => {
		var myHeaders = new Headers();
		myHeaders.append("Content-Type", "application/json");

		var raw = JSON.stringify({
			content: content,
			order: Object.values(notes).length + 1,
		});

		var requestOptions = {
			method: "POST",
			headers: myHeaders,
			body: raw,
			redirect: "follow",
		};
		let response = await fetch(`${url}/note`, requestOptions);
		if (response.ok) {
			console.log(await response.json());
		} else {
			console.error(response.status);
		}
	};
	const deleteNote = async (id) => {
		let response = await fetch(`${url}/note/${id}`, { method: "DELETE" });
		if (response.ok) {
			console.log(await response.json());
		} else {
			console.error(response.status);
		}
	};
	useEffect(() => {
		fetchData();
	}, []);

	if (!notes) {
		return <p>wait</p>;
	} else
		return (
			<div>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<form onSubmit={handleSubmit}>
					<input type="text" value={inputValue} onChange={inputValueChange} />
					<input type="submit" value="Add" />
				</form>
				<main>
					<div>
						{Object.values(notes).map((note) => {
							return (
								<div key={note._id}>
									<p>{note.content}</p>
									<button onClick={() => deleteNote(note._id)}>Delete</button>
								</div>
							);
						})}
					</div>
				</main>
			</div>
		);
}
